package com.petcaresystem.enities.enu;

public enum NotificationType {
    APPOINTMENT_REMINDER,
    APPOINTMENT_CONFIRMATION,
    APPOINTMENT_CANCELLATION,
    PAYMENT_REMINDER,
    PAYMENT_CONFIRMATION,
    INVOICE_GENERATED,
    SERVICE_COMPLETED,
    PROMOTIONAL,
    SYSTEM_ALERT,
    GENERAL
}
